//FETCH DATA
export const FETCH_NAME_REQUEST = "FETCH_NAME_REQUEST";
export const FETCH_NAME_SUCCESS = "FETCH_NAME_SUCCESS";
export const FETCH_NAME_ERROR = "FETCH_NAME_ERROR";

//CREATE NEWDATA
export const CREATE_NAME_REQUEST = "CREATE_NAME_REQUEST";
export const CREATE_NAME_SUCCESS = "CREATE_NAME_SUCCESS";
export const CREATE_NAME_ERROR = "CREATE_NAME_ERROR";

//DELETE DATA
export const DELETE_NAME_SUCCESS = "DELETE_NAME_SUCCESS ";

//UPDATE DATA
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
